In [ ]:
import json
import pandas as pd
import os
print(os.getcwd())

/home/abhishek/build/BerlinBikeWatchDE/analysis

In [3]:
def load_places_from_local(filepath):
  with open(filepath) as f:
    data = json.load(f)
  return pd.DataFrame(data["places"])

In [6]:
df1 = load_places_from_local("/home/abhishek/build/BerlinBikeWatchDE/data/raw/bike_stations/dt=2026-08-28/hour=12/20260828T120713Z.json")

df2 = load_places_from_local("/home/abhishek/build/BerlinBikeWatchDE/data/raw/bike_stations/dt=2026-08-28/hour=12/20260828T120719Z.json")

In [ ]:
df1["name"]

0                              EDEKA Schmitt (S Halensee)
1       Möllendorffstraße/Rathaus Lichtenberg (Mobilit...
2                      S Nöldnerplatz (Mobilitätsstation)
3                                 S+U Lichtenberg (EDEKA)
4                         Verwaltungsstandort Lichtenberg
                              ...
4184                                           BIKE 17421
4185                                          BIKE 100402
4186                                          BIKE 380336
4187                                          BIKE 380772
4188                                           BIKE 18769
Name: name, Length: 4189, dtype: str

In [18]:
bike_in_df1 = df1[df1["name"] == "BIKE 17421"]

bike_in_df1

,uid,lat,lng,name,booked_bikes,bikes,bikes_available_to_rent,active_place,bike_racks,free_racks,special_racks,free_special_racks,maintenance,terminal_type,place_type,rack_locks,fetched_at
4184,641718169,52.525302,13.428324,BIKE 17421,0,1,1,1,0,0,0,0,False,,12,False,2026-08-28T12:07:13.289609+00:00

In [19]:
bike_in_df2 = df2[df2["name"] == "BIKE 17421"]

bike_in_df2

,uid,lat,lng,name,booked_bikes,bikes,bikes_available_to_rent,active_place,bike_racks,free_racks,special_racks,free_special_racks,maintenance,terminal_type,place_type,rack_locks,fetched_at
4179,641718169,52.525302,13.428324,BIKE 17421,0,1,1,1,0,0,0,0,False,,12,False,2026-08-28T12:07:18.739183+00:00